// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6TqmMKvAqOOubWoCw8M9JEauVxq8M32w',
    appId: '1:306974107353:web:e9592d76f546fb013200c8',
    messagingSenderId: '306974107353',
    projectId: 'flutter-foodapp-4f11d',
    authDomain: 'flutter-foodapp-4f11d.firebaseapp.com',
    storageBucket: 'flutter-foodapp-4f11d.appspot.com',
    measurementId: 'G-F9SXX0YLX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ukIycfpdShLQeVIV0v-ur7MBX2vxp-8',
    appId: '1:306974107353:android:a302cbcd7e7cd0473200c8',
    messagingSenderId: '306974107353',
    projectId: 'flutter-foodapp-4f11d',
    storageBucket: 'flutter-foodapp-4f11d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowQJSuF9aqSRBvuvk3_U1YsyshrhgIzY',
    appId: '1:306974107353:ios:c82a00e7d4126f533200c8',
    messagingSenderId: '306974107353',
    projectId: 'flutter-foodapp-4f11d',
    storageBucket: 'flutter-foodapp-4f11d.appspot.com',
    androidClientId: '306974107353-n943pl97opkfc9jpv4nqdc6gu3ff7u5b.apps.googleusercontent.com',
    iosClientId: '306974107353-758l2mnmmf2s8ktavpapfpcdau5mjh1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDowQJSuF9aqSRBvuvk3_U1YsyshrhgIzY',
    appId: '1:306974107353:ios:ee100013db6c47783200c8',
    messagingSenderId: '306974107353',
    projectId: 'flutter-foodapp-4f11d',
    storageBucket: 'flutter-foodapp-4f11d.appspot.com',
    androidClientId: '306974107353-n943pl97opkfc9jpv4nqdc6gu3ff7u5b.apps.googleusercontent.com',
    iosClientId: '306974107353-8o50u6erk4s7e5bgcjeqt5au6tv63mar.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication0.RunnerTests',
  );
}
